name             'rb-druid-indexer'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-druid-indexer'
version          '0.2.0'
